"""empty message

Revision ID: 1713fa18e6c6
Revises: e9c8b3ae9bd7
Create Date: 2021-05-30 21:39:46.355972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1713fa18e6c6'
down_revision = 'e9c8b3ae9bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phrase_verb', table_name='phrase_verbs')
    op.drop_index('translation', table_name='phrase_verbs')
    op.drop_table('phrase_verbs')
    op.add_column('phrasal_verbs_vocabulary', sa.Column('phrasal_verb', sa.String(length=60), nullable=False))
    op.drop_index('phrase_verb', table_name='phrasal_verbs_vocabulary')
    op.drop_index('translation', table_name='phrasal_verbs_vocabulary')
    op.create_unique_constraint('unique_phrasal_verb_translation', 'phrasal_verbs_vocabulary', ['phrasal_verb', 'translation'])
    op.drop_column('phrasal_verbs_vocabulary', 'phrase_verb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrasal_verbs_vocabulary', sa.Column('phrase_verb', mysql.VARCHAR(length=60), nullable=False))
    op.drop_constraint('unique_phrasal_verb_translation', 'phrasal_verbs_vocabulary', type_='unique')
    op.create_index('translation', 'phrasal_verbs_vocabulary', ['translation'], unique=False)
    op.create_index('phrase_verb', 'phrasal_verbs_vocabulary', ['phrase_verb'], unique=False)
    op.drop_column('phrasal_verbs_vocabulary', 'phrasal_verb')
    op.create_table('phrase_verbs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phrase_verb', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('translation', mysql.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('translation', 'phrase_verbs', ['translation'], unique=False)
    op.create_index('phrase_verb', 'phrase_verbs', ['phrase_verb'], unique=False)
    # ### end Alembic commands ###
