"""empty message

Revision ID: c5d8fb82cbb4
Revises: 9d01e2c43848
Create Date: 2020-06-30 13:58:43.394459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5d8fb82cbb4'
down_revision = '9d01e2c43848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('pet')
    op.drop_index('login', table_name='users')
    op.drop_table('users')
    op.drop_index('name', table_name='person')
    op.drop_table('person')
    op.drop_constraint('interval_words_ibfk_1', 'interval_words', type_='foreignkey')
    op.create_foreign_key(None, 'interval_words', 'user', ['user_id'], ['id'])
    op.alter_column('vocabulary', 'translation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               nullable=False)
    op.drop_constraint('words_ibfk_1', 'words', type_='foreignkey')
    op.create_foreign_key(None, 'words', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.create_foreign_key('words_ibfk_1', 'words', 'users', ['user_id'], ['id'])
    op.alter_column('vocabulary', 'translation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               nullable=True)
    op.drop_constraint(None, 'interval_words', type_='foreignkey')
    op.create_foreign_key('interval_words_ibfk_1', 'interval_words', 'users', ['user_id'], ['id'])
    op.create_table('person',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'person', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('login', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('login', 'users', ['login'], unique=True)
    op.create_table('pet',
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='pet_ibfk_1'),
    sa.PrimaryKeyConstraint('person_id', 'name'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
