"""empty message

Revision ID: e9c8b3ae9bd7
Revises: c5d8fb82cbb4
Create Date: 2020-12-13 17:40:23.285389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9c8b3ae9bd7'
down_revision = 'c5d8fb82cbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finished_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_words',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('word_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addition_time', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='finished_words_ibfk_1'),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary.id'], name='finished_words_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'word_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
